2021-06-29 20:12:53 Error: Testing LogError() basic function
2021-06-29 20:12:53 Error: Testing with multi-line string
2021-06-30 16:16:23 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known',
  'enabled' => true,
)
Request URL: /Tasks/index
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/lib/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('default')
#3 /var/www/html/lib/Cake/Model/Model.php(1126): Model->setDataSource('default')
#4 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('tasks')
#5 /var/www/html/lib/Cake/Model/Model.php(2903): Model->getDataSource()
#6 /var/www/html/lib/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#7 /var/www/html/app/Controller/TasksController.php(31): Model->find('all', Array)
#8 [internal function]: TasksController->index()
#9 /var/www/html/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(TasksController), Array)
#10 /var/www/html/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#11 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest), Object(CakeResponse))
#12 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2021-06-30 16:19:58 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known',
  'enabled' => true,
)
Request URL: /Tasks/index
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/lib/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('default')
#3 /var/www/html/lib/Cake/Model/Model.php(1126): Model->setDataSource('default')
#4 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('tasks')
#5 /var/www/html/lib/Cake/Model/Model.php(2903): Model->getDataSource()
#6 /var/www/html/lib/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#7 /var/www/html/app/Controller/TasksController.php(31): Model->find('all', Array)
#8 [internal function]: TasksController->index()
#9 /var/www/html/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(TasksController), Array)
#10 /var/www/html/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#11 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest), Object(CakeResponse))
#12 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2021-06-30 16:31:09 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known',
  'enabled' => true,
)
Request URL: /Tasks/index
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/lib/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('test')
#3 /var/www/html/lib/Cake/Model/Model.php(1126): Model->setDataSource('test')
#4 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('tasks')
#5 /var/www/html/lib/Cake/Model/Model.php(2903): Model->getDataSource()
#6 /var/www/html/lib/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#7 /var/www/html/app/Controller/TasksController.php(31): Model->find('all', Array)
#8 [internal function]: TasksController->index()
#9 /var/www/html/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(TasksController), Array)
#10 /var/www/html/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#11 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest), Object(CakeResponse))
#12 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2021-06-30 16:33:34 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known',
  'enabled' => true,
)
Request URL: /Tasks/index
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/lib/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('test')
#3 /var/www/html/lib/Cake/Model/Model.php(1126): Model->setDataSource('test')
#4 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('tasks')
#5 /var/www/html/lib/Cake/Model/Model.php(2903): Model->getDataSource()
#6 /var/www/html/lib/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#7 /var/www/html/app/Controller/TasksController.php(31): Model->find('all', Array)
#8 [internal function]: TasksController->index()
#9 /var/www/html/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(TasksController), Array)
#10 /var/www/html/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#11 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest), Object(CakeResponse))
#12 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2021-06-30 16:33:58 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] No such file or directory',
  'enabled' => true,
)
Request URL: /Tasks/index
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/lib/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('test')
#3 /var/www/html/lib/Cake/Model/Model.php(1126): Model->setDataSource('test')
#4 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('tasks')
#5 /var/www/html/lib/Cake/Model/Model.php(2903): Model->getDataSource()
#6 /var/www/html/lib/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#7 /var/www/html/app/Controller/TasksController.php(31): Model->find('all', Array)
#8 [internal function]: TasksController->index()
#9 /var/www/html/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(TasksController), Array)
#10 /var/www/html/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#11 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest), Object(CakeResponse))
#12 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2021-06-30 16:36:30 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] No such file or directory',
  'enabled' => true,
)
Request URL: /Tasks/index
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/lib/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('test')
#3 /var/www/html/lib/Cake/Model/Model.php(1126): Model->setDataSource('test')
#4 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('tasks')
#5 /var/www/html/lib/Cake/Model/Model.php(2903): Model->getDataSource()
#6 /var/www/html/lib/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#7 /var/www/html/app/Controller/TasksController.php(31): Model->find('all', Array)
#8 [internal function]: TasksController->index()
#9 /var/www/html/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(TasksController), Array)
#10 /var/www/html/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#11 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest), Object(CakeResponse))
#12 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2021-06-30 16:37:01 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] No such file or directory',
  'enabled' => true,
)
Request URL: /Tasks/index
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/lib/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('test')
#3 /var/www/html/lib/Cake/Model/Model.php(1126): Model->setDataSource('test')
#4 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('tasks')
#5 /var/www/html/lib/Cake/Model/Model.php(2903): Model->getDataSource()
#6 /var/www/html/lib/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#7 /var/www/html/app/Controller/TasksController.php(31): Model->find('all', Array)
#8 [internal function]: TasksController->index()
#9 /var/www/html/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(TasksController), Array)
#10 /var/www/html/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#11 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest), Object(CakeResponse))
#12 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2021-06-30 16:37:04 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] No such file or directory',
  'enabled' => true,
)
Request URL: /Tasks/index
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/lib/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('test')
#3 /var/www/html/lib/Cake/Model/Model.php(1126): Model->setDataSource('test')
#4 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('tasks')
#5 /var/www/html/lib/Cake/Model/Model.php(2903): Model->getDataSource()
#6 /var/www/html/lib/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#7 /var/www/html/app/Controller/TasksController.php(31): Model->find('all', Array)
#8 [internal function]: TasksController->index()
#9 /var/www/html/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(TasksController), Array)
#10 /var/www/html/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#11 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest), Object(CakeResponse))
#12 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2021-06-30 16:37:19 Error: [MissingTableException] Table tasks for model Task was not found in datasource default.
Exception Attributes: array (
  'table' => 'tasks',
  'class' => 'Task',
  'ds' => 'default',
)
Request URL: /Tasks/index
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('tasks')
#1 /var/www/html/lib/Cake/Model/Model.php(2903): Model->getDataSource()
#2 /var/www/html/lib/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#3 /var/www/html/app/Controller/TasksController.php(31): Model->find('all', Array)
#4 [internal function]: TasksController->index()
#5 /var/www/html/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(TasksController), Array)
#6 /var/www/html/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest), Object(CakeResponse))
#8 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2021-06-30 16:37:37 Error: [MissingControllerException] Controller class TaskController could not be found.
Exception Attributes: array (
  'class' => 'TaskController',
  'plugin' => NULL,
)
Request URL: /Task/index
Stack Trace:
#0 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2021-06-30 16:39:21 Error: [MissingTableException] Table mails for model Mail was not found in datasource default.
Exception Attributes: array (
  'table' => 'mails',
  'class' => 'Mail',
  'ds' => 'default',
)
Request URL: /Mails/create
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('mails')
#1 /var/www/html/lib/Cake/Model/Model.php(1355): Model->getDataSource()
#2 /var/www/html/lib/Cake/View/Helper/FormHelper.php(207): Model->schema()
#3 /var/www/html/lib/Cake/View/Helper/FormHelper.php(459): FormHelper->_introspectModel('Mail', 'fields')
#4 /var/www/html/app/View/Mails/create.ctp(1): FormHelper->create('Mail', Array)
#5 /var/www/html/lib/Cake/View/View.php(935): include('/var/www/html/a...')
#6 /var/www/html/lib/Cake/View/View.php(897): View->_evaluate('/var/www/html/a...', Array)
#7 /var/www/html/lib/Cake/View/View.php(466): View->_render('/var/www/html/a...')
#8 /var/www/html/lib/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#9 /var/www/html/lib/Cake/Routing/Dispatcher.php(192): Controller->render()
#10 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MailsController), Object(CakeRequest), Object(CakeResponse))
#11 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2021-06-30 16:41:25 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] No such file or directory',
  'enabled' => true,
)
Request URL: /Mails/create
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/lib/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('test')
#3 /var/www/html/lib/Cake/Model/Model.php(1126): Model->setDataSource('test')
#4 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('mails')
#5 /var/www/html/lib/Cake/Model/Model.php(1355): Model->getDataSource()
#6 /var/www/html/lib/Cake/View/Helper/FormHelper.php(207): Model->schema()
#7 /var/www/html/lib/Cake/View/Helper/FormHelper.php(459): FormHelper->_introspectModel('Mail', 'fields')
#8 /var/www/html/app/View/Mails/create.ctp(1): FormHelper->create('Mail', Array)
#9 /var/www/html/lib/Cake/View/View.php(935): include('/var/www/html/a...')
#10 /var/www/html/lib/Cake/View/View.php(897): View->_evaluate('/var/www/html/a...', Array)
#11 /var/www/html/lib/Cake/View/View.php(466): View->_render('/var/www/html/a...')
#12 /var/www/html/lib/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#13 /var/www/html/lib/Cake/Routing/Dispatcher.php(192): Controller->render()
#14 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MailsController), Object(CakeRequest), Object(CakeResponse))
#15 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2021-06-30 16:41:44 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] No such file or directory',
  'enabled' => true,
)
Request URL: /Mails/create
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/lib/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('test')
#3 /var/www/html/lib/Cake/Model/Model.php(1126): Model->setDataSource('test')
#4 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('mails')
#5 /var/www/html/lib/Cake/Model/Model.php(1355): Model->getDataSource()
#6 /var/www/html/lib/Cake/View/Helper/FormHelper.php(207): Model->schema()
#7 /var/www/html/lib/Cake/View/Helper/FormHelper.php(459): FormHelper->_introspectModel('Mail', 'fields')
#8 /var/www/html/app/View/Mails/create.ctp(1): FormHelper->create('Mail', Array)
#9 /var/www/html/lib/Cake/View/View.php(935): include('/var/www/html/a...')
#10 /var/www/html/lib/Cake/View/View.php(897): View->_evaluate('/var/www/html/a...', Array)
#11 /var/www/html/lib/Cake/View/View.php(466): View->_render('/var/www/html/a...')
#12 /var/www/html/lib/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#13 /var/www/html/lib/Cake/Routing/Dispatcher.php(192): Controller->render()
#14 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MailsController), Object(CakeRequest), Object(CakeResponse))
#15 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2021-06-30 16:42:09 Error: [MissingDatasourceConfigException] The datasource configuration "t" was not found in database.php
Exception Attributes: array (
  'config' => 't',
)
Request URL: /Mails/create
Stack Trace:
#0 /var/www/html/lib/Cake/Model/ConnectionManager.php(91): ConnectionManager::_getConnectionObject('t')
#1 /var/www/html/lib/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('t')
#2 /var/www/html/lib/Cake/Model/Model.php(1126): Model->setDataSource('t')
#3 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('mails')
#4 /var/www/html/lib/Cake/Model/Model.php(1355): Model->getDataSource()
#5 /var/www/html/lib/Cake/View/Helper/FormHelper.php(207): Model->schema()
#6 /var/www/html/lib/Cake/View/Helper/FormHelper.php(459): FormHelper->_introspectModel('Mail', 'fields')
#7 /var/www/html/app/View/Mails/create.ctp(1): FormHelper->create('Mail', Array)
#8 /var/www/html/lib/Cake/View/View.php(935): include('/var/www/html/a...')
#9 /var/www/html/lib/Cake/View/View.php(897): View->_evaluate('/var/www/html/a...', Array)
#10 /var/www/html/lib/Cake/View/View.php(466): View->_render('/var/www/html/a...')
#11 /var/www/html/lib/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#12 /var/www/html/lib/Cake/Routing/Dispatcher.php(192): Controller->render()
#13 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MailsController), Object(CakeRequest), Object(CakeResponse))
#14 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}
2021-06-30 16:42:17 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] No such file or directory',
  'enabled' => true,
)
Request URL: /Mails/create
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/lib/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('test')
#3 /var/www/html/lib/Cake/Model/Model.php(1126): Model->setDataSource('test')
#4 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('mails')
#5 /var/www/html/lib/Cake/Model/Model.php(1355): Model->getDataSource()
#6 /var/www/html/lib/Cake/View/Helper/FormHelper.php(207): Model->schema()
#7 /var/www/html/lib/Cake/View/Helper/FormHelper.php(459): FormHelper->_introspectModel('Mail', 'fields')
#8 /var/www/html/app/View/Mails/create.ctp(1): FormHelper->create('Mail', Array)
#9 /var/www/html/lib/Cake/View/View.php(935): include('/var/www/html/a...')
#10 /var/www/html/lib/Cake/View/View.php(897): View->_evaluate('/var/www/html/a...', Array)
#11 /var/www/html/lib/Cake/View/View.php(466): View->_render('/var/www/html/a...')
#12 /var/www/html/lib/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#13 /var/www/html/lib/Cake/Routing/Dispatcher.php(192): Controller->render()
#14 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MailsController), Object(CakeRequest), Object(CakeResponse))
#15 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2021-06-30 16:43:22 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] No such file or directory',
  'enabled' => true,
)
Request URL: /Mails/create
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/lib/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('test')
#3 /var/www/html/lib/Cake/Model/Model.php(1126): Model->setDataSource('test')
#4 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('mails')
#5 /var/www/html/lib/Cake/Model/Model.php(1355): Model->getDataSource()
#6 /var/www/html/lib/Cake/View/Helper/FormHelper.php(207): Model->schema()
#7 /var/www/html/lib/Cake/View/Helper/FormHelper.php(459): FormHelper->_introspectModel('Mail', 'fields')
#8 /var/www/html/app/View/Mails/create.ctp(1): FormHelper->create('Mail', Array)
#9 /var/www/html/lib/Cake/View/View.php(935): include('/var/www/html/a...')
#10 /var/www/html/lib/Cake/View/View.php(897): View->_evaluate('/var/www/html/a...', Array)
#11 /var/www/html/lib/Cake/View/View.php(466): View->_render('/var/www/html/a...')
#12 /var/www/html/lib/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#13 /var/www/html/lib/Cake/Routing/Dispatcher.php(192): Controller->render()
#14 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MailsController), Object(CakeRequest), Object(CakeResponse))
#15 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2021-06-30 16:43:35 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] No such file or directory',
  'enabled' => true,
)
Request URL: /Mails/create
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/lib/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('test')
#3 /var/www/html/lib/Cake/Model/Model.php(1126): Model->setDataSource('test')
#4 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('mails')
#5 /var/www/html/lib/Cake/Model/Model.php(1355): Model->getDataSource()
#6 /var/www/html/lib/Cake/View/Helper/FormHelper.php(207): Model->schema()
#7 /var/www/html/lib/Cake/View/Helper/FormHelper.php(459): FormHelper->_introspectModel('Mail', 'fields')
#8 /var/www/html/app/View/Mails/create.ctp(1): FormHelper->create('Mail', Array)
#9 /var/www/html/lib/Cake/View/View.php(935): include('/var/www/html/a...')
#10 /var/www/html/lib/Cake/View/View.php(897): View->_evaluate('/var/www/html/a...', Array)
#11 /var/www/html/lib/Cake/View/View.php(466): View->_render('/var/www/html/a...')
#12 /var/www/html/lib/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#13 /var/www/html/lib/Cake/Routing/Dispatcher.php(192): Controller->render()
#14 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MailsController), Object(CakeRequest), Object(CakeResponse))
#15 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2021-06-30 16:46:07 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known',
  'enabled' => true,
)
Request URL: /Mails/create
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/lib/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('test')
#3 /var/www/html/lib/Cake/Model/Model.php(1126): Model->setDataSource('test')
#4 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('mails')
#5 /var/www/html/lib/Cake/Model/Model.php(1355): Model->getDataSource()
#6 /var/www/html/lib/Cake/View/Helper/FormHelper.php(207): Model->schema()
#7 /var/www/html/lib/Cake/View/Helper/FormHelper.php(459): FormHelper->_introspectModel('Mail', 'fields')
#8 /var/www/html/app/View/Mails/create.ctp(1): FormHelper->create('Mail', Array)
#9 /var/www/html/lib/Cake/View/View.php(935): include('/var/www/html/a...')
#10 /var/www/html/lib/Cake/View/View.php(897): View->_evaluate('/var/www/html/a...', Array)
#11 /var/www/html/lib/Cake/View/View.php(466): View->_render('/var/www/html/a...')
#12 /var/www/html/lib/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#13 /var/www/html/lib/Cake/Routing/Dispatcher.php(192): Controller->render()
#14 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MailsController), Object(CakeRequest), Object(CakeResponse))
#15 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2021-06-30 16:46:14 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known',
  'enabled' => true,
)
Request URL: /Mails/create
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/lib/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('test')
#3 /var/www/html/lib/Cake/Model/Model.php(1126): Model->setDataSource('test')
#4 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('mails')
#5 /var/www/html/lib/Cake/Model/Model.php(1355): Model->getDataSource()
#6 /var/www/html/lib/Cake/View/Helper/FormHelper.php(207): Model->schema()
#7 /var/www/html/lib/Cake/View/Helper/FormHelper.php(459): FormHelper->_introspectModel('Mail', 'fields')
#8 /var/www/html/app/View/Mails/create.ctp(1): FormHelper->create('Mail', Array)
#9 /var/www/html/lib/Cake/View/View.php(935): include('/var/www/html/a...')
#10 /var/www/html/lib/Cake/View/View.php(897): View->_evaluate('/var/www/html/a...', Array)
#11 /var/www/html/lib/Cake/View/View.php(466): View->_render('/var/www/html/a...')
#12 /var/www/html/lib/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#13 /var/www/html/lib/Cake/Routing/Dispatcher.php(192): Controller->render()
#14 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MailsController), Object(CakeRequest), Object(CakeResponse))
#15 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2021-06-30 16:46:53 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known',
  'enabled' => true,
)
Request URL: /Mails/create
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/lib/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('test')
#3 /var/www/html/lib/Cake/Model/Model.php(1126): Model->setDataSource('test')
#4 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('mails')
#5 /var/www/html/lib/Cake/Model/Model.php(1355): Model->getDataSource()
#6 /var/www/html/lib/Cake/View/Helper/FormHelper.php(207): Model->schema()
#7 /var/www/html/lib/Cake/View/Helper/FormHelper.php(459): FormHelper->_introspectModel('Mail', 'fields')
#8 /var/www/html/app/View/Mails/create.ctp(1): FormHelper->create('Mail', Array)
#9 /var/www/html/lib/Cake/View/View.php(935): include('/var/www/html/a...')
#10 /var/www/html/lib/Cake/View/View.php(897): View->_evaluate('/var/www/html/a...', Array)
#11 /var/www/html/lib/Cake/View/View.php(466): View->_render('/var/www/html/a...')
#12 /var/www/html/lib/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#13 /var/www/html/lib/Cake/Routing/Dispatcher.php(192): Controller->render()
#14 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MailsController), Object(CakeRequest), Object(CakeResponse))
#15 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2021-06-30 16:47:23 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known',
  'enabled' => true,
)
Request URL: /Mails/create
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/lib/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('test')
#3 /var/www/html/lib/Cake/Model/Model.php(1126): Model->setDataSource('test')
#4 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('mails')
#5 /var/www/html/lib/Cake/Model/Model.php(1355): Model->getDataSource()
#6 /var/www/html/lib/Cake/View/Helper/FormHelper.php(207): Model->schema()
#7 /var/www/html/lib/Cake/View/Helper/FormHelper.php(459): FormHelper->_introspectModel('Mail', 'fields')
#8 /var/www/html/app/View/Mails/create.ctp(1): FormHelper->create('Mail', Array)
#9 /var/www/html/lib/Cake/View/View.php(935): include('/var/www/html/a...')
#10 /var/www/html/lib/Cake/View/View.php(897): View->_evaluate('/var/www/html/a...', Array)
#11 /var/www/html/lib/Cake/View/View.php(466): View->_render('/var/www/html/a...')
#12 /var/www/html/lib/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#13 /var/www/html/lib/Cake/Routing/Dispatcher.php(192): Controller->render()
#14 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MailsController), Object(CakeRequest), Object(CakeResponse))
#15 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2021-06-30 16:47:54 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] No such file or directory',
  'enabled' => true,
)
Request URL: /Mails/create
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/lib/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('test')
#3 /var/www/html/lib/Cake/Model/Model.php(1126): Model->setDataSource('test')
#4 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('mails')
#5 /var/www/html/lib/Cake/Model/Model.php(1355): Model->getDataSource()
#6 /var/www/html/lib/Cake/View/Helper/FormHelper.php(207): Model->schema()
#7 /var/www/html/lib/Cake/View/Helper/FormHelper.php(459): FormHelper->_introspectModel('Mail', 'fields')
#8 /var/www/html/app/View/Mails/create.ctp(1): FormHelper->create('Mail', Array)
#9 /var/www/html/lib/Cake/View/View.php(935): include('/var/www/html/a...')
#10 /var/www/html/lib/Cake/View/View.php(897): View->_evaluate('/var/www/html/a...', Array)
#11 /var/www/html/lib/Cake/View/View.php(466): View->_render('/var/www/html/a...')
#12 /var/www/html/lib/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#13 /var/www/html/lib/Cake/Routing/Dispatcher.php(192): Controller->render()
#14 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MailsController), Object(CakeRequest), Object(CakeResponse))
#15 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2021-06-30 16:48:07 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known',
  'enabled' => true,
)
Request URL: /Mails/create
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/lib/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('test')
#3 /var/www/html/lib/Cake/Model/Model.php(1126): Model->setDataSource('test')
#4 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('mails')
#5 /var/www/html/lib/Cake/Model/Model.php(1355): Model->getDataSource()
#6 /var/www/html/lib/Cake/View/Helper/FormHelper.php(207): Model->schema()
#7 /var/www/html/lib/Cake/View/Helper/FormHelper.php(459): FormHelper->_introspectModel('Mail', 'fields')
#8 /var/www/html/app/View/Mails/create.ctp(1): FormHelper->create('Mail', Array)
#9 /var/www/html/lib/Cake/View/View.php(935): include('/var/www/html/a...')
#10 /var/www/html/lib/Cake/View/View.php(897): View->_evaluate('/var/www/html/a...', Array)
#11 /var/www/html/lib/Cake/View/View.php(466): View->_render('/var/www/html/a...')
#12 /var/www/html/lib/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#13 /var/www/html/lib/Cake/Routing/Dispatcher.php(192): Controller->render()
#14 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MailsController), Object(CakeRequest), Object(CakeResponse))
#15 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2021-06-30 16:48:54 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] Connection refused',
  'enabled' => true,
)
Request URL: /Mails/create
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/lib/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('test')
#3 /var/www/html/lib/Cake/Model/Model.php(1126): Model->setDataSource('test')
#4 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('mails')
#5 /var/www/html/lib/Cake/Model/Model.php(1355): Model->getDataSource()
#6 /var/www/html/lib/Cake/View/Helper/FormHelper.php(207): Model->schema()
#7 /var/www/html/lib/Cake/View/Helper/FormHelper.php(459): FormHelper->_introspectModel('Mail', 'fields')
#8 /var/www/html/app/View/Mails/create.ctp(1): FormHelper->create('Mail', Array)
#9 /var/www/html/lib/Cake/View/View.php(935): include('/var/www/html/a...')
#10 /var/www/html/lib/Cake/View/View.php(897): View->_evaluate('/var/www/html/a...', Array)
#11 /var/www/html/lib/Cake/View/View.php(466): View->_render('/var/www/html/a...')
#12 /var/www/html/lib/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#13 /var/www/html/lib/Cake/Routing/Dispatcher.php(192): Controller->render()
#14 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MailsController), Object(CakeRequest), Object(CakeResponse))
#15 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2021-06-30 16:49:07 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] Connection refused',
  'enabled' => true,
)
Request URL: /Mails/create
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/lib/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('test')
#3 /var/www/html/lib/Cake/Model/Model.php(1126): Model->setDataSource('test')
#4 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('mails')
#5 /var/www/html/lib/Cake/Model/Model.php(1355): Model->getDataSource()
#6 /var/www/html/lib/Cake/View/Helper/FormHelper.php(207): Model->schema()
#7 /var/www/html/lib/Cake/View/Helper/FormHelper.php(459): FormHelper->_introspectModel('Mail', 'fields')
#8 /var/www/html/app/View/Mails/create.ctp(1): FormHelper->create('Mail', Array)
#9 /var/www/html/lib/Cake/View/View.php(935): include('/var/www/html/a...')
#10 /var/www/html/lib/Cake/View/View.php(897): View->_evaluate('/var/www/html/a...', Array)
#11 /var/www/html/lib/Cake/View/View.php(466): View->_render('/var/www/html/a...')
#12 /var/www/html/lib/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#13 /var/www/html/lib/Cake/Routing/Dispatcher.php(192): Controller->render()
#14 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MailsController), Object(CakeRequest), Object(CakeResponse))
#15 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2021-06-30 16:49:16 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known',
  'enabled' => true,
)
Request URL: /Mails/create
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/lib/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('test')
#3 /var/www/html/lib/Cake/Model/Model.php(1126): Model->setDataSource('test')
#4 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('mails')
#5 /var/www/html/lib/Cake/Model/Model.php(1355): Model->getDataSource()
#6 /var/www/html/lib/Cake/View/Helper/FormHelper.php(207): Model->schema()
#7 /var/www/html/lib/Cake/View/Helper/FormHelper.php(459): FormHelper->_introspectModel('Mail', 'fields')
#8 /var/www/html/app/View/Mails/create.ctp(1): FormHelper->create('Mail', Array)
#9 /var/www/html/lib/Cake/View/View.php(935): include('/var/www/html/a...')
#10 /var/www/html/lib/Cake/View/View.php(897): View->_evaluate('/var/www/html/a...', Array)
#11 /var/www/html/lib/Cake/View/View.php(466): View->_render('/var/www/html/a...')
#12 /var/www/html/lib/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#13 /var/www/html/lib/Cake/Routing/Dispatcher.php(192): Controller->render()
#14 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MailsController), Object(CakeRequest), Object(CakeResponse))
#15 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2021-06-30 16:51:16 Error: [MissingTableException] Table mails for model Mail was not found in datasource test.
Exception Attributes: array (
  'table' => 'mails',
  'class' => 'Mail',
  'ds' => 'test',
)
Request URL: /Mails/create
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('mails')
#1 /var/www/html/lib/Cake/Model/Model.php(1355): Model->getDataSource()
#2 /var/www/html/lib/Cake/View/Helper/FormHelper.php(207): Model->schema()
#3 /var/www/html/lib/Cake/View/Helper/FormHelper.php(459): FormHelper->_introspectModel('Mail', 'fields')
#4 /var/www/html/app/View/Mails/create.ctp(1): FormHelper->create('Mail', Array)
#5 /var/www/html/lib/Cake/View/View.php(935): include('/var/www/html/a...')
#6 /var/www/html/lib/Cake/View/View.php(897): View->_evaluate('/var/www/html/a...', Array)
#7 /var/www/html/lib/Cake/View/View.php(466): View->_render('/var/www/html/a...')
#8 /var/www/html/lib/Cake/Controller/Controller.php(954): View->render(NULL, NULL)
#9 /var/www/html/lib/Cake/Routing/Dispatcher.php(192): Controller->render()
#10 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(MailsController), Object(CakeRequest), Object(CakeResponse))
#11 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2021-06-30 17:09:56 Error: Fatal Error (1): Call to undefined method TopicTest::assetFalse() in [/var/www/html/app/Test/Case/Model/TopicTest.php, line 45]
2021-06-30 17:09:56 Error: [FatalErrorException] Call to undefined method TopicTest::assetFalse()
Stack Trace:
#0 /var/www/html/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to undefin...', '/var/www/html/a...', 45)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', '/var/www/html/a...', 45, Array)
#2 /var/www/html/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', '/var/www/html/a...', 45, Array)
#3 /var/www/html/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2021-07-01 12:32:54 Error: [MissingTableException] Table tasks for model Task was not found in datasource test.
Exception Attributes: array (
  'table' => 'tasks',
  'class' => 'Task',
  'ds' => 'test',
)
Request URL: /Tasks/index
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('tasks')
#1 /var/www/html/lib/Cake/Model/Model.php(2903): Model->getDataSource()
#2 /var/www/html/lib/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#3 /var/www/html/app/Controller/TasksController.php(31): Model->find('all', Array)
#4 [internal function]: TasksController->index()
#5 /var/www/html/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(TasksController), Array)
#6 /var/www/html/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest), Object(CakeResponse))
#8 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2021-07-01 12:33:06 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known',
  'enabled' => true,
)
Request URL: /Tasks/index
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(260): Mysql->connect()
#1 /var/www/html/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/html/lib/Cake/Model/Model.php(3477): ConnectionManager::getDataSource('default')
#3 /var/www/html/lib/Cake/Model/Model.php(1126): Model->setDataSource('default')
#4 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('tasks')
#5 /var/www/html/lib/Cake/Model/Model.php(2903): Model->getDataSource()
#6 /var/www/html/lib/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#7 /var/www/html/app/Controller/TasksController.php(31): Model->find('all', Array)
#8 [internal function]: TasksController->index()
#9 /var/www/html/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(TasksController), Array)
#10 /var/www/html/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#11 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest), Object(CakeResponse))
#12 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2021-07-01 12:34:30 Error: [MissingTableException] Table tasks for model Task was not found in datasource test.
Exception Attributes: array (
  'table' => 'tasks',
  'class' => 'Task',
  'ds' => 'test',
)
Request URL: /Tasks/index
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('tasks')
#1 /var/www/html/lib/Cake/Model/Model.php(2903): Model->getDataSource()
#2 /var/www/html/lib/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#3 /var/www/html/app/Controller/TasksController.php(31): Model->find('all', Array)
#4 [internal function]: TasksController->index()
#5 /var/www/html/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(TasksController), Array)
#6 /var/www/html/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest), Object(CakeResponse))
#8 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2021-07-01 12:34:42 Error: [MissingControllerException] Controller class Teat.phpController could not be found.
Exception Attributes: array (
  'class' => 'Teat.phpController',
  'plugin' => NULL,
)
Request URL: /teat.php
Stack Trace:
#0 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2021-07-01 14:40:39 Error: Fatal Error (4): syntax error, unexpected '=', expecting ')' in [/var/www/html/app/Test/Case/Controller/TopicsControllerTest.php, line 102]
2021-07-01 14:40:39 Error: [FatalErrorException] syntax error, unexpected '=', expecting ')'
Stack Trace:
#0 /var/www/html/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/html/a...', 102)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/html/a...', 102, Array)
#2 /var/www/html/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/html/a...', 102, Array)
#3 /var/www/html/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2021-07-01 14:40:54 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' in [/var/www/html/app/Test/Case/Controller/TopicsControllerTest.php, line 103]
2021-07-01 14:40:54 Error: [FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')'
Stack Trace:
#0 /var/www/html/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/html/a...', 103)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/html/a...', 103, Array)
#2 /var/www/html/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/html/a...', 103, Array)
#3 /var/www/html/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2021-07-01 14:48:13 Error: [MissingTableException] Table tasks for model Task was not found in datasource test.
Exception Attributes: array (
  'table' => 'tasks',
  'class' => 'Task',
  'ds' => 'test',
)
Request URL: /Tasks/index
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Model.php(3499): Model->setSource('tasks')
#1 /var/www/html/lib/Cake/Model/Model.php(2903): Model->getDataSource()
#2 /var/www/html/lib/Cake/Model/Model.php(2875): Model->_readDataSource('all', Array)
#3 /var/www/html/app/Controller/TasksController.php(31): Model->find('all', Array)
#4 [internal function]: TasksController->index()
#5 /var/www/html/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(TasksController), Array)
#6 /var/www/html/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#7 /var/www/html/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(TasksController), Object(CakeRequest), Object(CakeResponse))
#8 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2021-07-01 14:48:23 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'
Stack Trace:
#0 /var/www/html/lib/Cake/Model/Datasource/DboSource.php(2923): PDOStatement->execute()
#1 /var/www/html/lib/Cake/TestSuite/Fixture/CakeTestFixture.php(289): DboSource->insertMulti('categories', Array, Array)
#2 /var/www/html/lib/Cake/TestSuite/Fixture/CakeFixtureManager.php(212): CakeTestFixture->insert(Object(Mysql))
#3 /var/www/html/lib/Cake/TestSuite/CakeTestCase.php(80): CakeFixtureManager->load(Object(TopicsControllerTest))
#4 /var/www/html/app/vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php(779): CakeTestCase->run(Object(PHPUnit_Framework_TestResult))
#5 /var/www/html/app/vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php(749): PHPUnit_Framework_TestSuite->runTest(Object(TopicsControllerTest), Object(PHPUnit_Framework_TestResult))
#6 /var/www/html/app/vendor/phpunit/phpunit/PHPUnit/TextUI/TestRunner.php(350): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult), false, Array, Array, false)
#7 /var/www/html/lib/Cake/TestSuite/CakeTestRunner.php(60): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#8 /var/www/html/lib/Cake/TestSuite/CakeTestSuiteCommand.php(96): CakeTestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#9 /var/www/html/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php(243): CakeTestSuiteCommand->run(Array)
#10 /var/www/html/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php(96): CakeTestSuiteDispatcher->_runTestCase()
#11 /var/www/html/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php(113): CakeTestSuiteDispatcher->dispatch()
#12 /var/www/html/app/webroot/test.php(98): CakeTestSuiteDispatcher::run()
#13 {main}
2021-07-01 19:36:59 Error: [MissingControllerException] Controller class Tsql.phpController could not be found.
Exception Attributes: array (
  'class' => 'Tsql.phpController',
  'plugin' => NULL,
)
Request URL: /tsql.php
Stack Trace:
#0 /var/www/html/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2021-07-02 07:35:42 Error: Fatal Error (4): syntax error, unexpected 'else' (T_ELSE) in [/var/www/html/app/View/Sql/index.ctp, line 4]
2021-07-02 07:35:42 Error: [FatalErrorException] syntax error, unexpected 'else' (T_ELSE)
Request URL: /sql
Stack Trace:
#0 /var/www/html/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/html/a...', 4)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/html/a...', 4, Array)
#2 /var/www/html/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/html/a...', 4, Array)
#3 /var/www/html/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2021-07-02 07:36:15 Error: Fatal Error (1): Call to undefined method App::users() in [/var/www/html/app/Model/User.php, line 2]
2021-07-02 07:36:15 Error: [FatalErrorException] Call to undefined method App::users()
Request URL: /sql
Stack Trace:
#0 /var/www/html/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to undefin...', '/var/www/html/a...', 2)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', '/var/www/html/a...', 2, Array)
#2 /var/www/html/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', '/var/www/html/a...', 2, Array)
#3 /var/www/html/lib/Cake/Core/App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
